# Generated by Django 4.2.7 on 2023-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0002_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='direccion',
        ),
        migrations.AddField(
            model_name='reporte',
            name='direccion',
            field=models.CharField(default='Valor predeterminado', max_length=100),
        ),
    ]
