# Generated by Django 4.2.7 on 2023-12-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0003_remove_empleado_direccion_reporte_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
