# Generated by Django 4.2.7 on 2023-12-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0005_usuario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(default='root', max_length=128),
        ),
    ]
