# Generated by Django 4.2.7 on 2023-12-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0007_alter_usuario_contraseña_alter_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
    ]
