# Generated by Django 4.2.7 on 2023-12-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0008_remove_usuario_user_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='contraseña',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
