# Generated by Django 4.2.7 on 2023-12-04 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporte', '0009_empleado_contraseña_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='comentarios',
            field=models.TextField(null=True),
        ),
    ]
